= General docker and Cloud guidelines and notes

== Docker
=== Inititial setup
Setting up a network:
----
docker network create pearlbaynet
----

==== AI-Repo
building docker image :
----
docker build -t pearlbay/stockairepo:latest .
----
run AI-Repo container :
----
docker run -e "TZ=EUROPE/BERLIN" -p 8080:8080 --net=pearlbaynet pearlbay/stockairepo
----
==== Oracle DB
building docker image :
----
docker build -t "madhead/docker-oracle-xe" .
----
run Oracle DB container :
----
docker run -p 8089:8080 -p 1521:1521 --net=pearlbaynet -d madhead/docker-oracle-xe
----
AI-Repo container application.properties settings (local) :
----
spring.datasource.url=jdbc:oracle:thin:@172.18.0.2:1521:XE
spring.datasource.username=system
spring.datasource.password=oracle
spring.liquibase.change-log=classpath:liquibase/db.changelog.xml
spring.jpa.properties.hibernate.default_schema=STOCKAIREPO
----


== Cloud

==== Docker HUB
login :
----
docker login
----
tag image :
----
docker tag <image id> <dockerusername>/<image name>
----
push image to docker hub :
----
docker push <repository title>:<tag>
----
stockairepo image push example :
----
docker push renegaat/stockairepo:latest
----
stockairepo image pull example :
----
docker pull renegaat/stockairepo:latest
----
==== AWS
==== Google Cloud
==== Kubernetes
get kubernetes nodes :
----
kubectl get nodes
----
create deployment into node (example) :
----
kubectl create deployment
----
get kubernetes deployments :
----
kubectl get deployments
----
get kubernetes pods
----
kubectl get pods
----
describe kubernetes pods
----
kubectl describe pods
----
creating a kubernetes proxy :
----
kubectl proxy
----
kubernetes example extract pod name into variable POD_NAME
----
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME
----
logging stdout from pod POD_NAME 
----
kubectl logs $POD_NAME
----
execute command in container. (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec $POD_NAME <command>
----
execute command in container (example bash). (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec -ti $POD_NAME bash
----
=== General Notes
==== Docker HUB
- Set the repository to private if access denied problem for docker push
<to validate>
