apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-pod
spec:
  selector:
    matchLabels:
      name: ora-container
  template:
    metadata:
      labels:
         name: ora-container
    spec:
      containers:
        - name: oracle-container
          image: madhead-minikube/docker-oracle-xe
          imagePullPolicy: Never
      restartPolicy: Always