== Kubernetes
=== Setup local application cluster (minikube)
switch to minikube docker context :
----
eval $(minikube -p minikube docker-env)
----
=== Setup remote application cluster
=== General Notes and commands
get kubernetes nodes :
----
kubectl get nodes
----
create deployment into node (example) :
----
kubectl create deployment
----
get kubernetes deployments :
----
kubectl get deployments
----
get kubernetes pods
----
kubectl get pods
----
describe kubernetes pods
----
kubectl describe pods
----
creating a kubernetes proxy :
----
kubectl proxy
----
kubernetes example extract pod name into variable POD_NAME
----
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME
----
logging stdout from pod POD_NAME
----
kubectl logs $POD_NAME
----
execute command in container. (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec $POD_NAME <command>
----
execute command in container (example bash). (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec -ti $POD_NAME bash
----
kubernetes get services :
----
kubectl get services
----
kubernetes expose a pod :
----
kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
----
kubernetes describe a service :
----
kubectl describe services/<service_name>
----
kubernetes get the note port of a service :
----
export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')
echo NODE_PORT=$NODE_PORT
----
curl export service from outside kubernetes :
----
curl $(minikube ip):$NODE_PORT
----
delete a pending pod in kubernetes :
----
kubectl get deployments --all-namespaces
kubectl delete deployment <NAME>
----

