== Kubernetes
=== Setup local application cluster (minikube)
step by step instructions ( oracle ) :
----
start minikube
set docker daemon scope to minikube
start minikube dashboard ( new terminal )
check available docker images
create deployment ( kubectl create -f oracle_container.yaml )
create load balancer ( kubectl expose deployment  stockai-oracle-pod --type=LoadBalancer --port=1521 )
start minikube tunnel
check connection settings in pom.xml
----
step by step instructions ( Stock-AI application ) :
----
start minikube
set docker daemon scope to minikube
start minikube dashboard ( new terminal )
check available docker images
create deployment ( kubectl create -f stockairepo_container.yaml )
create load balancer ( kubectl expose deployment  stockai-repo-pod --type=LoadBalancer --port=8080 )
start minikube tunnel
check DB connection settings in local app configuration
----
switch to minikube docker context :
----
eval $(minikube -p minikube docker-env)
----
build docker images in minikube context if necessary :
----
docker build -t pearlbay/stockairepo_minikube:latest .
docker build -t madhead_minikube/docker-oracle-xe .
----
kubernetes .yaml deployment file ( oracle minikube container sample ) :
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-pod
spec:
  selector:
    matchLabels:
      name: ora-container
  template:
    metadata:
      labels:
         name: ora-container
    spec:
      containers:
        - name: oracle-container
          image: madhead-minikube/docker-oracle-xe
          imagePullPolicy: Never
      restartPolicy: Always
----
kubernetes .yaml service file ( oracle minicube container sample ) :
----
apiVersion: v1
kind: Service
metadata:
  name: stockai-pod
  namespace: default
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 31080
----
kubernetes expose a service :
----
kubectl expose deployment stockai-pod --type=LoadBalancer --port=1521
----
kubernetes show active services :
----
kubectl get svc
----
minikube create tunnel :
----
minikube tunnel
----
kubernetes create deployment (oracle container sample) :
----
kubectl create -f oracle_container.yaml
----
kubernetes delete deployment (oracle container sample) :
----
kubectl delete -f oracle_container.yaml
----
=== Setup remote application cluster
=== General Notes and commands
get kubernetes nodes :
----
kubectl get nodes
----
create deployment into node (example) :
----
kubectl create deployment
----
get kubernetes deployments :
----
kubectl get deployments
----
get kubernetes pods
----
kubectl get pods
----
describe kubernetes pods
----
kubectl describe pods
----
creating a kubernetes proxy :
----
kubectl proxy
----
kubernetes example extract pod name into variable POD_NAME
----
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME
----
logging stdout from pod POD_NAME
----
kubectl logs $POD_NAME
----
execute command in container. (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec $POD_NAME <command>
----
execute command in container (example bash). (Note it is not necessary to mention container when there is only one in the pod) :
----
kubectl exec -ti $POD_NAME bash
----
kubernetes get services :
----
kubectl get services
----
kubernetes expose a pod :
----
kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
----
kubernetes describe a service :
----
kubectl describe services/<service_name>
----
kubernetes get the note port of a service :
----
export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')
echo NODE_PORT=$NODE_PORT
----
curl export service from outside kubernetes :
----
curl $(minikube ip):$NODE_PORT
----
delete a pending pod in kubernetes :
----
kubectl get deployments --all-namespaces
kubectl delete deployment <NAME>
----
=== General Notes and Help
When kubectl command in gcloud shell gets error :
----
The connection to the server localhost:8080 was refused - did you specify the right host or port?
----
Set kubeconfig like :
----
gcloud container clusters get-credentials stock-ai --region europe-central2-a
----
