
= Infrastructure : Docker

== Container handling

List containers :
----
docker container ls
----

Remove container :
----
docker rm <container>
----

Clear container cache:
----
docker container prune
----

Stop container :

----
docker container stop <container>
----

Start container :

----
docker run -p <hostport>:<containerport> --net=<networkname> <container>
----

Example :

----
docker run -p 8080:8080 --net=pearlbaynet pearlbay/stockairepo
----
----
docker run -e "TZ=EUROPE/BERLIN" -p 8080:8080 --net=pearlbaynet pearlbay/stockairepo
----
----
docker run -p 8089:8080 -p 1521:1521 -d madhead/docker-oracle-xe
----

Inspect container :
----
docker inspect <container>
----

== Image handling :
Create image :
----
docker build -t <tagname>:latest .
----
Example :
----
docker build -t pearlbay/stockairepo:latest .
----
building multiarchitecture image with buildx ( example stockairepo arm64 with push to docker hub )  :
----
*docker* buildx build --platform linux/arm64 -t renegaat/stockairepo:latest . --push
----
building multiarchitecture image with buildx ( example oraclexe arm64 with push to docker hub )  :
----
docker buildx build --platform linux/arm64 -t renegaat/docker-oracle-xe:latest . --push TODO
----
clear buildx cache :
----
docker buildx prune
----
Example (local minikube deployment, see notes below) :
----
docker build -t pearlbay/stockairepo_minikube:latest .
----
List images :
----
docker images
----
tag docker  image :
----
docker tag <image id> <dockerusername>/<image name>
----
tag image ( example EU GC oracle image ) :
----
docker tag e2070a28e1d1 eu.gcr.io/stockai-313609/madhead/docker-oracle-xe
----
Remove image examples :
----
docker rmi <image>
----
----
docker rmi <repository_name>:tag
----


Remove all images :
----
docker image prune
----



== Network

Create network :
----
docker network create <name>
----

Inspect network :
----
docker network inspect <name>
----

Inspect network example :
----
docker network inspect pealbaynet
----

== Troubleshooting
- for local minikube environment, build the image with minikube docker daemon
- container have to be in the same network to be able to communicate
- see docker network inspect command for ip configuration
- for oracle db client to work the timezone environment has to be set in container
- used FROM adoptopenjdk/openjdk11:latest in dockerfile to clear docker container problem on pi

