apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-oracle-pod
spec:
  selector:
    matchLabels:
      name: ora-container
  template:
    metadata:
      labels:
         name: ora-container
    spec:
      containers:
        - name: oracle-container
          image: madhead-minikube/docker-oracle-xe
          imagePullPolicy: Never
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stockai-pod
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521



