apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-pod
spec:
  selector:
    matchLabels:
      name: stockai-container
  template:
    metadata:
      labels:
        name: stockai-container
    spec:
      containers:
        - name: oracle-container
          image: madhead-minikube/docker-oracle-xe
          imagePullPolicy: Never
      restartPolicy: Always