apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-pod
spec:
  selector:
    matchLabels:
      name: stockai-pod
  template:
    metadata:
      labels:
         name: stockai-pod
    spec:
      containers:
        - name: oracle-container
          image: madhead-minikube/docker-oracle-xe
          imagePullPolicy: Never
        - name: stockairepo-container
          image: pearlbay-minikube/docker-stockairepo
          imagePullPolicy: Never
      restartPolicy: Always
