apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockai-pod
spec:
  selector:
    matchLabels:
      name: ai-repo-container
  template:
    metadata:
      labels:
        name: ai-repo-container
    spec:
      containers:
        - name: airepo-container
          image: pearlbay-minikube/stockairepo
          imagePullPolicy: Never
      restartPolicy: Always