https://github.com/sclorg/django-ex.git
# Docker Compose für Oracle XE 11gR2

## Was ist dies?

Dies lässt eine Oracle XE 11gR2 Datenbank innerhalb von Docker laufen.

Es ist eine angepasste Version dieses Docker-Files: https://github.com/madhead/docker-oracle-xe.


Alternativ :

https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles


## Vorbedingung

Als Vorbedingung mit `init.sh` das RPM für Oracle XE installieren. Dies muss nur einmal passieren.
Die Datei oracle-database-xe-18c-1.0-1.x86_64.rpm muss im container/resources Ordner liegen.


Die Datei kann lokal vom FTP heruntergeladen werden

----
curl -u admin:SS***** ftp://192.168.1.1/Elements/projects/stockai/resources/oracle-xe-11.2.0-1.0.x86_64.rpm.tar.gz -O
----

## Starten

----
docker-compose up
----

Anschließend mit SQL Developer oder aus IntelliJ wie folgt auf dei Datenbank zugreifen:

----
hostname: 192.168.23.9
port: 1521
sid: XE
username: system
password: oracle
----

Anhalten mit `Ctrl-C` auf der Kommandozeile.

## Shell in den Oracle XE Container

----
docker exec -i -t oraclexe_oraclexe_1 bash
----


## Container direkt starten

----
docker run -p 8089:8080 -p 1521:1521 container id
----

## Daten bereinigen

----
docker-compose rm -v
----

Nach dem nächsten Start wird die Datenbank wieder leer sein.

== Weitere Informationen

Auf Port 1521 ist die Datenbank verfügbar.


== Tips und Tricks (Alternativen zu compose-up)

Image bauen :

----
docker build -t "madhead/docker-oracle-xe" .
----

Container starten :

----
docker run -p 8089:8080 -p 1521:1521 madhead/docker-oracle-xe
----


== Fehler:

Keine Rechte bin/start.sh zu starten

----
chmod +x start.sh to set correct permission for shell script.
----

siehe https://stackoverflow.com/questions/38882654/docker-entrypoint-running-bash-script-gets-permission-denied






















