
# StockAiRepo


*Local Setup (docker configuration):*

*Remarks:*

The Configuration is as follows:

* Spring application in a docker container
* Postgres database running direct on the host
* user configuration see section below

*setup local postgres database (raspberry pi):*

* Install postgres database:
* setup user, db, schema, add user rights
* check db reachability from local machine
* check correct settings in pg_hba.conf
** host    all   all  172.17.0.0/16   md5
* check firewall settings

*spring container :*

Start stockairepo (remote/local):
----
docker run -e "TZ=EUROPE/BERLIN" -p 8081:8080 renegaat/stockairepo:latest
----

Build and Start stockairepo (local):
----
mvn package -pl /application/app-stockairepo
----
----
docker build -t pearlbay/stockairepo:latest .
----
----
docker run -e "TZ=EUROPE/BERLIN" -p 8080:8080 --net=pearlbaynet pearlbay/stockairepo
----
application.properties:
----
spring.datasource.url=jdbc:postgresql://172.17.0.1:5432/stockaidb
spring.datasource.username=stockaiuser
spring.datasource.password=stockaipassword
spring.liquibase.change-log=classpath:liquibase/dbchangelog.xml
spring.jpa.properties.hibernate.default_schema=STOCKAIREPO
----

*check remote api access (remote example)*
----
curl "http://192.168.1.152:8081/stocktimeseriesdata/v1/stocktimeseriesdata?symbol=MSFT&function=TIME_SERIES_DAILY"
----
----
curl "http://192.168.1.152:8081/stocktimeseriesdata/v1/stocktimeseriesdata?symbol=MSFT&from=1990-04-05%2011%3A30%3A00&until=2020-05-05%2000%3A00%3A00&function=TIME_SERIES_DAILY"
----
*Help:*
check docker network configuration:
----
docker network inspect pearlbaynet
----

To reset the environment stop and remove db container.

Example Rest Service Requests :
----
/stocktimeseriesdata/v1/stocktimeseriesdata?symbol=MSFT&from=2020-04-05%2011%3A30%3A00&until=2020-05-05%2000%3A00%3A00&function=TIME_SERIES_DAILY
----
To reset database (manually):
----
DELETE FROM stockairepo.databasechangelog;
DELETE FROM stockairepo.databasechangeloglock;
DROP TABLE stockairepo.metadata;
DROP TABLE stockairepo.stocktimeseriesdata;
DROP TABLE stockairepo.timeseries;

drop sequence stockairepo.stock_timeseries_data_id_seq;
drop sequence stockairepo.metadata_id_seq;
drop sequence stockairepo.timeseries_id_seq;
----
to delete database content:
----
delete from STOCKAIREPO.TIMESERIES;
delete from STOCKAIREPO.STOCKTIMESERIESDATA;
delete from STOCKAIREPO.METADATA;
----